---
- name: "Genarete keys configs"
  ansible.builtin.template:
    src: section_key.j2
    dest: "{{ nsd_dir_etc }}/main.d/key.conf"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
  notify:
    - test config nsd
    - restart nsd

- name: "Genarete pattern configs"
  ansible.builtin.template:
    src: section_pattern.j2
    dest: "{{ nsd_dir_etc }}/main.d/pattern.conf"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
  notify:
    - test config nsd
    - restart nsd

- name: "Genarete zone configs"
  ansible.builtin.template:
    src: section_zone.j2
    dest: "{{ nsd_dir_etc }}/main.d/zone.conf"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
  notify:
    - test config nsd
    - restart nsd

- name: "Generate server config file"
  ansible.builtin.template:
    src: section_server.j2
    dest: "{{ nsd_dir_etc }}/main.d/server.conf"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
  notify:
    - test config nsd
    - restart nsd

- name: "Generate remote config file"
  ansible.builtin.template:
    src: section_remote.j2
    dest: "{{ nsd_dir_etc }}/main.d/remote.conf"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
  notify:
    - test config nsd
    - restart nsd

- name: "Generate custom main config file"
  ansible.builtin.template:
    src: nsd.conf.custom.j2
    dest: "{{ nsd_dir_etc }}/main.d/custom.conf"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    force: false
  notify:
    - test config nsd
    - restart nsd

- name: "Generate main config file"
  ansible.builtin.template:
    src: nsd.conf.j2
    dest: "{{ nsd_dir_etc }}/nsd.conf"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
    validate: "{{ nsd_bin_check_conf }} %s"
  notify:
    - test config nsd
    - restart nsd
