---
- name: "genarete keys configs"
  template:
    src: section_key.j2
    dest: "{{ nsd_dir_etc }}/main.d/key.{{ key.key }}"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
  with_dict: "{{ nsd_conf_keys }}"
  notify:
    - test config nsd
    - restart nsd
  loop_control:
    loop_var: key

- name: "genarete pattern configs"
  template:
    src: section_pattern.j2
    dest: "{{ nsd_dir_etc}}/main.d/pattern.{{ pattern.key }}"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
  with_dict: "{{ nsd_conf_patterns }}"
  notify:
    - test config nsd
    - restart nsd
  loop_control:
    loop_var: pattern

- name: "genarete zone configs"
  template:
    src: section_zone.j2
    dest: "{{ nsd_dir_etc}}/main.d/zone.{{ zone.key }}"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
  with_dict: "{{ nsd_conf_zones }}"
  notify:
    - test config nsd
    - restart nsd
  loop_control:
    loop_var: zone

- name: "generate server config file"
  template:
    src: section_server.j2
    dest: "{{ nsd_dir_etc}}/main.d/server.conf"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
  notify:
    - test config nsd
    - restart nsd

- name: "generate remote config file"
  template:
    src: section_remote.j2
    dest: "{{ nsd_dir_etc}}/main.d/remote.conf"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
  notify:
    - test config nsd
    - restart nsd

- name: "generate custom main config file"
  template:
    src: nsd.conf.custom.j2
    dest: "{{ nsd_dir_etc}}/nsd.conf.custom"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    force: no
  notify:
    - test config nsd
    - restart nsd

- name: "generate main config file"
  template:
    src: nsd.conf.j2
    dest: "{{ nsd_dir_etc}}/nsd.conf"
    mode: 0640
    owner: root
    group: "{{ nsd_user }}"
    backup: "{{ nsd_backup }}"
    validate: "{{ nsd_bin_check_conf }} %s"
  notify:
    - test config nsd
    - restart nsd
