---
# tasks file for nsd

- name: "Set OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_os_family }}.yml"
  tags:
    - nsd
    - nsd:package
    - nsd:setup
    - nsd:config
    - nsd:service

- name: "Include package tasks"
  ansible.builtin.include_tasks: packages-{{ ansible_os_family }}.yml
  tags:
    - nsd
    - nsd:package

- name: "Include setup tasks"
  ansible.builtin.include_tasks: setup.yml
  tags:
    - nsd
    - nsd:setup

- name: "Include config tasks"
  ansible.builtin.include_tasks: config.yml
  tags:
    - nsd
    - nsd:config

- name: "Include service tasks"
  ansible.builtin.include_tasks: service.yml
  tags:
    - nsd
    - nsd:service
