---
# tasks file for nsd

- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_os_family }}.yml"
  tags:
    - nsd
    - nsd:package
    - nsd:setup
    - nsd:config
    - nsd:service

- name: include package tasks
  include: packages-{{ ansible_os_family }}.yml
  tags:
    - nsd
    - nsd:package

- name: include setup tasks
  include: setup.yml
  tags:
    - nsd
    - nsd:setup

- name: include config tasks
  include: config.yml
  tags:
    - nsd
    - nsd:config

- name: include service tasks
  include: service.yml
  tags:
    - nsd
    - nsd:service
