---
# tasks file for nsd

- name: "Set OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_os_family }}.yml"
  tags:
    - always

- name: "Include package tasks"
  ansible.builtin.include_tasks:
    file: packages-{{ ansible_os_family }}.yml
    apply:
      tags:
        - nsd
        - nsd:package
  tags:
    - always

- name: "Include setup tasks"
  ansible.builtin.include_tasks:
    file: setup.yml
    apply:
      tags:
        - nsd
        - nsd:setup
  tags:
    - always

- name: "Include config tasks"
  ansible.builtin.include_tasks:
    file:  config.yml
    apply:
      tags:
        - nsd
        - nsd:config
  tags:
    - always

- name: "Include service tasks"
  ansible.builtin.include_tasks:
    file:  service.yml
    apply:
      tags:
        - nsd
        - nsd:service
  tags:
    - always
