---

- name: "Create directories"
  ansible.builtin.file:
    path: "{{ nsd_dir_etc }}/{{ directory }}"
    state: directory
    owner: "{{ nsd_user }}"
    group: "{{ nsd_group }}"
    mode: 0750
  loop:
    - main.d
    - conf.d
    - server.d
  loop_control:
    loop_var: directory

- name: "Check nsd-control"
  ansible.builtin.stat:
    path: '{{ nsd_dir_etc }}/nsd_control.key'
  register: control_key

- name: "Init nsd-control"
  ansible.builtin.command: "{{ nsd_bin_control_setup }}"
  when: not control_key.stat.exists
