---
# handlers file for nsd
- name: test config nsd   # noqa name[casing]
  ansible.builtin.command: "{{ nsd_bin_check_conf }} {{ nsd_dir_etc }}/nsd.conf"

- name: restart nsd       # noqa name[casing]
  ansible.builtin.service:
    name: "{{ nsd_service }}"
    state: restarted
  when: not nsd_test
