---
- name: Converge
  hosts: all
  roles:
    - role: hudecof.packages
      packages_centos_epel: True
      packages_ubuntu_multiverse: True
      packages_ubuntu_universe: True
    - role: hudecof.filter-plugins
    - role: hudecof.nsd
      nsd_test: True
